
//I2C
#define I2C_MASTER_FREQ_HZ 400000
#define SDA_PIN  GPIO_NUM_21
#define SCL_PIN  GPIO_NUM_22

//SDcard
#define MISO_PIN GPIO_NUM_19
#define MOSI_PIN GPIO_NUM_23
#define SCK_PIN  GPIO_NUM_18
#define CS_PIN   GPIO_NUM_5