
//I2C
#define I2C_MASTER_FREQ_HZ 400000
#define SDA_PIN  GPIO_NUM_21
#define SCL_PIN  GPIO_NUM_22

//SDcard
#define MISO_PIN GPIO_NUM_19
#define MOSI_PIN GPIO_NUM_23
#define SCK_PIN  GPIO_NUM_18
#define CS_PIN   GPIO_NUM_5

//Button
#define BUTTON_1_PIN GPIO_NUM_16

//Motors
#define MOTOR_1_PWM   GPIO_NUM_15
#define MOTOR_1_DIR_1 GPIO_NUM_12
#define MOTOR_1_DIR_2 GPIO_NUM_13
#define MOTOR_2_PWM   GPIO_NUM_2
#define MOTOR_2_DIR_1 GPIO_NUM_14
#define MOTOR_2_DIR_2 GPIO_NUM_27